version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${UIPORT}:${UIPORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${PVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
       aliases:
        - post
      front_net:
       aliases:
        - post
  comment:
    image: ${USERNAME}/comment:${CVER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
       aliases:
        - comment
      front_net:
        aliases:
         - comment
volumes:
  post_db:

networks:
   back_net:
     ipam:
       config:
       - subnet: 10.0.2.0/24
   front_net:
     ipam:
       config:
       - subnet: 10.0.1.0/24
