version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:6.6.2
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
       aliases:
       - elasticsearch

  kibana:
    image: kibana:6.6.2
    ports:
      - "5601:5601"
    networks:
      - back_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net 

networks:
   back_net:
     ipam:
       config:
       - subnet: 10.0.2.0/24
   front_net:
     ipam:
       config:
       - subnet: 10.0.1.0/24

